name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1
  audio_session: ^0.1.7
  just_audio: ^0.9.24
  flutter_tts: ^3.3.3
  device_info_plus: ^9.0.2
  android_content_provider: ^0.3.0
  permission_handler : ^10.3.0
  rxdart: ^0.27.2
  audio_service:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true