name: audio_service
description: Flutter plugin to play audio in the background while the screen is off.
version: 0.5.2
homepage: https://github.com/ryanheise/audio_service

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.22.6
  flutter_isolate: ^1.0.0+10
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ryanheise.audioservice
    pluginClass: AudioServicePlugin
